apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: go-argo-app-hpa
  namespace: argo-rollouts
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: go-argo-app
  minReplicas: 2  # Minimum number of replicas
  maxReplicas: 10  # Maximum number of replicas
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80  