apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrics-server
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metrics-server  # Make sure this matches the label on the pod template
  template:
    metadata:
      labels:
        app: metrics-server  # Same label here as in the selector
  containers:
    - name: metrics-server
      image: k8s.gcr.io/metrics-server/metrics-server:v0.6.1  # Use the appropriate image version
      args:
      - --kubelet-insecure-tls
      ports:
        - containerPort: 443
