apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrics-server
  namespace: kube-system
spec:
  selector: 
    matchLabels:
      app: go-argo-app
  template:
    spec:
      containers:
        - name: metrics-server
          args:
            - --kubelet-insecure-tls
